### ISSUE TITLE
Error using netcdflib from Example

### ISSUE THREAD

**Issue by ckberinger** [oceanobservatories/ooi-data-explorations#63]
I tried to run the adcp_data example in Matlab and got the error below. I put in my own credentials and changed the metadata and it still had this error. How can I troubleshoot this?

Error using netcdflib
The NetCDF library encountered an error during execution of 'open' function - 'Not a valid data type
or _FillValue type mismatch (NC_EBADTYPE)'.

Error in netcdf.open (line 67)
        [varargout{:}] = netcdflib ( 'open', filename, varargin{1} );

Error in internal.matlab.imagesci.nc/openToRead (line 1278)
            this.ncRootid = netcdf.open(this.Filename,'NOWRITE');

Error in internal.matlab.imagesci.nc (line 121)
                    this.openToRead();

Error in ncread (line 61)
ncObj   = internal.matlab.imagesci.nc(ncFile);

Error in M2M_Data (line 116)
    ncTime = ncread(source, variables(1).name);

Error in adcp_data (line 47)
[adcp_variables, adcp_mtime, netcdfFilenames] = M2M_Data(variables, nclist);  %This will use the
opendap to read in the data from remote files

**Comment by crisien** [comment]
What version of Matlab are you running? Have you tried uncommenting line 46 in example_adcp.m, commenting out line 47 and rerunning the example? If this doesn't work try changing line 102 in M2M_Data.m from 
nc_urls = strcat(thredds_url, "/", nclist);  % string array 
to 
nc_urls = strcat(thredds_url, "/", nclist,"#fillmismatch");  % string array
If this doesn't work try 
nc_urls = strcat("[fillmismatch]",thredds_url, "/", nclist);  % string array

**Comment by ckberinger** [comment]
I am running R2020b. The uncommenting of line 46 (and commenting of 47) worked great, thank you!

**Comment by crisien** [comment]
Great. Glad that worked. Let me know if you encounter any other issues.
