### ISSUE TITLE
collections deprecation

### ISSUE THREAD

**Issue by s-pearce** [oceanobservatories/ooi-data-explorations#71]
@cwingard 

just FYI, collections.Mapping is deprecated from Python 3.3 and will stop working in Python 3.9.

Python says now you should import collections.abc. E.g.
```
from collections.abc import Mapping
isinstance(mydict, Mapping)
```

https://github.com/oceanobservatories/ooi-data-explorations/blob/cf63fb515e8b428791cb69538e17b4c97ac86dd6/python/ooi_data_explorations/common.py#L917

**Comment by cwingard** [comment]
Simple fix applied via PR#72
